# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[](#4C89F4)\
$directory\
[](fg:#4C89F4 bg:#324b64)\
$git_branch\
$git_status\
[](fg:#324b64 bg:#36B198)\
$nodejs\
$rust\
$golang\
$php\
$python\
$c\
[ ](fg:#36B198)\
 \
"""

[os]
format = "[](bg:#5C4033 fg:#EEEEEE)"
disabled = false

[username]
show_always = true
style_user = "bg:#5C4033 fg:#EEEEEE"
style_root = "bg:#5C4033 fg:#EEEEEE"
format = '[]($style)'

[directory]
style = "bold fg:#222222 bg:#4C89F4"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[directory.substitutions]
"~" = "󰜥 "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#EEEEEE bg:#324b64)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#EEEEEE bg:#324b64)]($style)'

[c]
symbol = " "
detect_extensions = ['c', 'cpp', 'h', 'hpp']
style = "bg:#86BBD8"
format = '[[ $symbol ($name $version) ](bold fg:#222222 bg:#36B198)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](bold fg:#222222 bg:#36B198)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](bold fg:#222222 bg:#36B198)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](bold fg:#222222 bg:#36B198)]($style)'

[python]
symbol = ""
style = "bg:#3B4252"
format = '[[ $symbol ($version) ](bold fg:#222222 bg:#36B198)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](bold fg:#222222 bg:#36B198)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#060606 bg:#e2e2e2)]($style)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
